AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: S3 → Lambda (Ingest) → SQS → Lambda (Metadata Extractor) → S3

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Architectures: [x86_64]

Resources:
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub coderoad-images-${AWS::AccountId}-${AWS::Region}
  
  CoderoadS3EventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: coderoad-s3-events-queue    

  IngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: ingest.lambda_handler
      Environment:
        Variables:
          INPUT_PREFIX: incoming/
          QUEUE_URL: !Ref CoderoadS3EventsQueue 
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub coderoad-images-${AWS::AccountId}-${AWS::Region}
        - SQSSendMessagePolicy:
            QueueName: coderoad-s3-events-queue
      Timeout: 10
             
      Events:
        ImageUpload:
          Type: S3
          Properties:
            Bucket: !Ref ImagesBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: incoming/ 
                  